{{- if .Values.agent.token }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccount: {{ template "fullname" . }}
      containers:
        - name: "{{ .Chart.Name }}-dind"
          image: docker:dind
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          volumeMounts:
            # Allows host volume mounts from buildkite-agent → docker-dind
            - mountPath: /buildkite/builds
              name: buildkite-builds
            {{- if .Values.registryCreds.gcrServiceAccountKey }}
            - name: service-key
              mountPath: /etc/service_key
            {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          env:
            # BUILDKITE AGENT ENV VARS
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: agent-token
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            - name: BUILDKITE_AGENT_META_DATA
              value: "{{ .Values.agent.meta }}"
            {{- if .Values.privateSshKey }}
            - name: SSH_PRIVATE_RSA_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: agent-ssh
            {{- end }}
            # EXTRA BUILDKITE AGENT ENV VARS
{{- if .Values.extraEnv }}{{ toYaml .Values.extraEnv | nindent 12 }}{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
{{- if .Values.volumeMounts }}{{ toYaml .Values.volumeMounts | nindent 12 }}{{- end }}
            # - name: var-run-docker-sock
            #   mountPath: /var/run/docker.sock
            # Allows host volume mounts from buildkite-agent → docker-dind
            - name: buildkite-builds
              mountPath: /buildkite/builds
            - name: buildkite-hooks
              mountPath: /buildkite/hooks
            {{- if .Values.registryCreds.gcrServiceAccountKey }}
            - name: service-key
              mountPath: /etc/service_key
            {{- end }}
            {{- if .Values.registryCreds.dockerConfig }}
            - name: docker-config
              mountPath: /root/.docker
            {{- end }}
      volumes:
{{- if .Values.volumes }}{{ toYaml .Values.volumes | nindent 8 }}{{- end }}
        # - name: var-run-docker-sock
        #   hostPath:
        #     path: /var/run/docker.sock
        - name: buildkite-builds
          emptyDir: {}
        - name: buildkite-hooks
          configMap:
            name: {{ template "fullname" . }}-hooks
        {{- if .Values.registryCreds.gcrServiceAccountKey }}
        - name: service-key
          secret:
            secretName: {{ template "fullname" . }}-gcr
        {{- end }}
        {{- if .Values.registryCreds.dockerConfig }}
        - name: docker-config
          secret:
            secretName: {{ template "fullname" . }}-registry
        {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
{{- end }}
